# -*- coding: utf-8 -*-
"""CS482FINALFINALFINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LmxUL60UhqXdlKUJ2qB79_iTlUzFXTi7
"""

import numpy as np
import matplotlib.pyplot as plt
import random
import scipy.stats as stats
import bisect
import time 



class Banknotes_Model:

  def __init__(self, r_fake, n, Q, seed = 123):
    # r = the number of types
    # n = the total number of cards of a type
    # k = the number of cards than have already been picked

    self.r_fake = r_fake
    self.n = n
    self.Q = Q
    self.seed = seed

  def draw_non_match(self, seed = 12):
    # chance of drawing from a number with a partial batch vs a card without a partial batch
      non_matchable_partials = self.non_matchable_partials
      all_non_matchable_cards = self.all_non_matchable_cards

      if self.all_non_matchable_cards == 0:
        return 0

      partial_batch_draw_chance = non_matchable_partials / self.all_non_matchable_cards
      draw_partial_batch = random.random() < partial_batch_draw_chance

      if draw_partial_batch:
        # draw a card from a partial batch
        # I have to figure out from which partial batch to draw
        # I can discretize the pdf and then do random.randint and a binary search
        partial_range_urn = random.randint(0, non_matchable_partials - 1)
        urn_index = bisect.bisect_left(self.partial_cumulative_weights, partial_range_urn)

        number_of_copies = self.partial_range_and_copies[urn_index][1]

        self.partial_cumulative_weights[urn_index] -= number_of_copies

        self.matchable_cards_partial += number_of_copies - 1

        non_matchable_partials -= number_of_copies
        all_non_matchable_cards -= number_of_copies

      else:
        self.matchable_normal_cards += self.r - 1

        all_non_matchable_cards -= self.r 


      self.non_matchable_partials = non_matchable_partials
      self.all_non_matchable_cards = all_non_matchable_cards



  def draw_initial(self, num_draws):

    if num_draws == 0:
      return

    #pre-initialize all the random numbers for our draws
    random_list = np.random.random(num_draws)

    # initialize allllll variables inside the function

    partial_cumulative_weights = self.partial_cumulative_weights
    partial_range_and_copies = self.partial_range_and_copies

    matchable_cards_partial = self.matchable_cards_partial
    matchable_normal_cards = self.matchable_normal_cards

    non_matchable_partials = self.non_matchable_partials
    all_non_matchable_cards = self.all_non_matchable_cards

    for i in range(num_draws):

      if all_non_matchable_cards == 0:
        return 0
    # chance of drawing from a number with a partial batch vs a card without a partial batch
      partial_batch_draw_chance = non_matchable_partials / all_non_matchable_cards
      draw_partial_batch = random_list[i] < partial_batch_draw_chance


      if draw_partial_batch:
        # draw a card from a partial batch
        # I have to figure out from which partial batch to draw
        # I can discretize the pdf and then do random.randint and a binary search
        partial_range_urn = random.randint(0, non_matchable_partials - 1)
        urn_index = bisect.bisect_left(partial_cumulative_weights, partial_range_urn)

        number_of_copies = self.partial_range_and_copies[urn_index][1]

        partial_cumulative_weights[urn_index] -= number_of_copies

        matchable_cards_partial += number_of_copies - 1

        non_matchable_partials -= number_of_copies
        all_non_matchable_cards -= number_of_copies

      else:
        matchable_normal_cards += self.r - 1

        all_non_matchable_cards -= self.r 

    


    # update all the variables in the class after all the draws
    self.non_matchable_partials = non_matchable_partials

    self.matchable_cards_partial = matchable_cards_partial
    self.matchable_normal_cards = matchable_normal_cards

    self.partial_cumulative_weights = partial_cumulative_weights
    self.partial_range_and_copies = partial_range_and_copies

    self.non_matchable_partials = non_matchable_partials
    self.all_non_matchable_cards = all_non_matchable_cards


  def run_simulation(self, k, seed = 123):
    # r = the number of types
    # n = the total number of cards of a type
    # k = the number of cards than have already been picked

    # Q is supposed to be an r x n matrix, but I can reduce it because of the nature of the dataset we are given
    # Q is an r x 2 matrix where each element in the first row shows the amount of repeats of the number in suit r,
    # which in our case is the bank that requested the bills
    # the 2nd row is the size of the partial batch in that group

    r_fake = self.r_fake
    n = self.n
    self.k = k
    Q = self.Q

    random.seed(seed)
    np.random.seed(seed)


    ### data parsing

    r = np.sum(Q[:, 0])
    self.r = np.sum(Q[:, 0])

    partials = Q[:, 1]
    partials.sort()

    tmp = []
    partials_sum = 0
    for i in range(len(partials)):
      val = partials[i] - partials_sum
      if val != 0:
        tmp.append([val, r_fake - i + r])
      partials_sum = partials[i]

    self.partial_range_and_copies = np.array(tmp)
    self.non_partial_range_and_copies = [n - partials_sum, r]

    if k > n:
      return 0

    cards_per_partial_size = self.partial_range_and_copies[:, 0] * self.partial_range_and_copies[:, 1]
    all_non_partial_cards = self.non_partial_range_and_copies[0] * self.non_partial_range_and_copies[1]
    drawn_numbers = k

    self.all_partial_cards = np.sum(cards_per_partial_size)
    self.absolutely_all_the_cards = self.all_partial_cards + all_non_partial_cards

    self.matchable_normal_cards = 0
    self.matchable_cards_partial = 0

    self.partial_cumulative_weights = np.cumsum(cards_per_partial_size)


    self.non_matchable_partials = self.all_partial_cards
    self.all_non_matchable_cards = self.non_matchable_partials + all_non_partial_cards  

#### first k drawings without a match
    self.draw_initial(k)
####

    done = False
    count = 0
    while not done:
      count += 1

      chances = (self.matchable_normal_cards + self.matchable_cards_partial) / (self.absolutely_all_the_cards - drawn_numbers)
      if random.random() < chances:
        # a matching number is picked
        return count

      # a unique number is picked
      self.draw_non_match()

    return count



if __name__ == "__main__":
  Q = np.array([[2, 2], [2, 5], [2, 6], [2, 4], [2, 1], [2, 1], [2, 0], [2, 1], [2, 1], [2, 1], [2, 1], [2, 1]]) * 1
  # the abstraction is kind of hard for me to understand but I think it does work
  # there are 11 copies of 1
  # there are 4 copies of 2
  # there are 3 copies of 3
  # there are 3 copies of 4 (hence 2, 3 because the range is from 3-4 with 3 copies per number)
  # there is 2 copies of 5
  # there is 1 copy of 6
  model = Banknotes_Model(12, 96000000, Q)
  print(model.run_simulation(0, random.randint(1, 100000)))

  Q = np.array([[2, 1], [20, 10000000], [2, 1], [2, 1], [2, 1], [2, 1], [2, 1], [2, 1], [2, 1], [2, 1], [2, 1], [2, 1]]) * 1
  # the abstraction is kind of hard for me to understand but I think it does work
  # there are 12 copies of each number from 0-1
  # there is 1 extra copy from 2-10000000
  model = Banknotes_Model(12, 96000000, Q)
  print(model.run_simulation(500000, 287))

  # I believe I have all of my code to analysis the bank note code excluding partial batches

  # I figure out Q by just looking at the bank data and figuring out what's the final letter each bank reaches
  # It's alphabetical except for O and Z, so there are 24 possible repeats.

  # The dataset I am using is the 1988A 1$ bills

  # The letters are arent used are O = 15 and Z = 26

  # again, excluding partial batches
  # A = G = 7, 0
  # B = W = 22, 51_200_000
  # C = D = 4, 89_600_000
  # D = D = 4, 76_800_000
  # E = Q = 16, 6_400_000
  # F = X = 23, 83_200_000
  # G = X = 23, 25_600_000
  # H = H = 8, 25_600_000
  # I = I = 9, 57_600_000
  # J = C = 3, 89_600_000
  # K = I = 9, 0
  # L = X = 23, 83_200_000

  # Q_real = np.array([7, 22, 4, 4, 16, 23, 23, 8, 9, 3, 9, 23])
  Q_real = np.array([[7, 0], [22, 51_200_000], [4, 89_600_000], [4, 76_800_000], [16, 6_400_000], [23, 83_200_000], [23, 25_600_000], [8, 25_600_000], [9, 57_600_000], [3, 89_600_000], [9, 0], [23, 83_200_000]])

  num_runs = 10
  zero_k = []
  ten_k = []
  twenty_k = []
  thirty_k = []
  hundred_k = []
  five_hundred_k = []

  everything_model = Banknotes_Model(12, 96000000, Q_real)

  begin_time = time.time()
  for i in range(num_runs):
    seed = i * 12345
    zero_k.append(everything_model.run_simulation(0, seed))
    ten_k.append(everything_model.run_simulation(10000, seed))
    twenty_k.append(everything_model.run_simulation(20000, seed))
    thirty_k.append(everything_model.run_simulation(30000, seed))
    hundred_k.append(everything_model.run_simulation(100000, seed))
    five_hundred_k.append(everything_model.run_simulation(500000, seed))
    # if (i % 20 == 0):
    #   print(i)
    print(i)


  end_time = time.time()

  # np.savetxt('zero_k.csv', zero_k, fmt='%d', delimiter=', ', header='k = 0', comments='')
  # np.savetxt('ten_k.csv', ten_k, fmt='%d', delimiter=', ', header='k = 10000', comments='')
  # np.savetxt('twenty_k.csv', twenty_k, fmt='%d', delimiter=', ', header='k = 20000', comments='')
  # np.savetxt('thirty_k.csv', thirty_k, fmt='%d', delimiter=', ', header='k = 30000', comments='')
  # np.savetxt('hundred_k.csv', hundred_k, fmt='%d', delimiter=', ', header='k = 100000', comments='')
  # np.savetxt('five_hundred_k.csv', five_hundred_k, fmt='%d', delimiter=', ', header='k = 500000', comments='')


  print("calculation time = " + str(end_time - begin_time))
  print(np.mean(zero_k))
  print(np.mean(ten_k))
  print(np.mean(twenty_k))
  print(np.mean(thirty_k))
  print(np.mean(hundred_k))
  print(np.mean(five_hundred_k))

  '''
  12887.8
  6924.7
  4283.5
  3454.8
  802.8
  108.4
  '''



  var = np.var(zero_k)
  confidence = 0.95
  n = len(zero_k)
  mean = np.mean(zero_k)
  std_err = stats.sem(zero_k)

  print("mean group size calculated correctly = " + str(np.mean(zero_k)))
  print("group size variance calculated correctly = " + str(np.var(zero_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_zero = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(ten_k)
  confidence = 0.95
  n = len(ten_k)
  mean = np.mean(ten_k)
  std_err = stats.sem(ten_k)

  print("mean group size calculated correctly = " + str(np.mean(ten_k)))
  print("group size variance calculated correctly = " + str(np.var(ten_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_ten = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(twenty_k)
  confidence = 0.95
  n = len(twenty_k)
  mean = np.mean(twenty_k)
  std_err = stats.sem(twenty_k)

  print("mean group size calculated correctly = " + str(np.mean(twenty_k)))
  print("group size variance calculated correctly = " + str(np.var(twenty_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_twenty = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(thirty_k)
  confidence = 0.95
  n = len(thirty_k)
  mean = np.mean(thirty_k)
  std_err = stats.sem(thirty_k)

  print("mean group size calculated correctly = " + str(np.mean(thirty_k)))
  print("group size variance calculated correctly = " + str(np.var(thirty_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_thirty = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(hundred_k)
  confidence = 0.95
  n = len(hundred_k)
  mean = np.mean(hundred_k)
  std_err = stats.sem(hundred_k)

  print("mean group size calculated correctly = " + str(np.mean(hundred_k)))
  print("group size variance calculated correctly = " + str(np.var(hundred_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_hundred = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(five_hundred_k)
  confidence = 0.95
  n = len(five_hundred_k)
  mean = np.mean(five_hundred_k)
  std_err = stats.sem(five_hundred_k)

  print("mean group size calculated correctly = " + str(np.mean(five_hundred_k)))
  print("group size variance calculated correctly = " + str(np.var(five_hundred_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_five_hundred = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  print(ci_string_size_zero)
  print(ci_string_size_ten)
  print(ci_string_size_twenty)
  print(ci_string_size_thirty)
  print(ci_string_size_hundred)
  print(ci_string_size_five_hundred)



# Confidence interval = 12887.8 +/- 4632.85
# Confidence interval = 6924.7 +/- 4705.255
# Confidence interval = 4283.5 +/- 2563.215
# Confidence interval = 3454.8 +/- 1687.054
# Confidence interval = 802.8 +/- 275.18
# Confidence interval = 108.4 +/- 86.907