# -*- coding: utf-8 -*-
"""CS482FINAL_Repeats_No_Partial_Batches.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IIQeQl7ApFXjQaRvs-iZQ-NwTe5OgKcs
"""

import numpy as np
import matplotlib.pyplot as plt
import random
import scipy.stats as stats



def run_simulation(r, n, k, Q, seed = 123):
  # r = the number of types
  # n = the total number of cards of a type
  # k = the number of cards than have already been picked

  # Q is supposed to be an r x n matrix, but I can reduce it because of the nature of the dataset we are given
  # Q is an r x 1 matrix where each element shows the amount of repeats of the number in suit r,
  # which in our case is the bank that requested the bills

  # I think this can be solved trivially because the repeat of all numbers is the same as a new suit
  # A copy of a number and a different suit of that same number are identical because
  # we're only trying to find the same number regardless of copy or suit

  random.seed(seed)

  r = np.sum(Q)

  if k > n:
    return 0

  total_numbers = n
  drawn_numbers = k


  done = False
  count = 0
  while not done:
    count += 1

    # drawing a random card without replacement
    # because we don't actually care what card we get and only if we get a match, we
    # can bin all the card numbers into card numbers than have not been picked and card numbers that have been picked
    # if we pick a not-picked card, we move it to picked and pick another card
    # if we pick a picked card, then we're done

    # the trick is how we consider the total amount of not-picked cards vs the total amount of "matching" numbers
    # we also need to consider that there is no replacement

    # this is where the number of suits comes in

    # if we pick a card x, and there are 5 total suits, then there are 4 potential x cards than can be picked,
    # and if any of those other suited cards are picked, we have a match and are done

    # my chances are the total numbers of cards where the number has been drawn / the total number of cards (without replacement)


    # chances = drawn_numbers * (r-1) / (total_numbers * r) # drawn_numbers * (r-1) / ((total_numbers * r) - drawn_numbers)
    chances = drawn_numbers * (r-1) / ((total_numbers * r) - drawn_numbers)
    if random.random() < chances:
      # a number that has already been drawn is picked
      return count
    else:
      # a unique number is picked
      drawn_numbers += 1


  return count



if __name__ == "__main__":
  Q = np.array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]) * 1
  print(run_simulation(12, 96000000, 500000, Q, random.randint(1, 100000)))

  # this is a test because I roughly know the expected number of people picked before someone share's a birthday
  # The only difference is that the birthday is picked without replacement, but for very large r, they're basically identical
  num_runs = 10000
  sum = 0
  Q_birthday = np.ones(9999)
  for i in range(num_runs):
    seed = i * 12345
    sum += run_simulation(9999, 365, 0, Q_birthday, seed)
  print(sum/num_runs)

  # I believe I have all of my code to analysis the bank note code excluding partial batches

  # I figure out Q by just looking at the bank data and figuring out what's the final letter each bank reaches
  # It's alphabetical except for O and Z, so there are 24 possible repeats.

  # The dataset I am using is the 1988A 1$ bills

  # The letters are arent used are O = 15 and Z = 26

  # again, excluding partial batches
  # A = G = 7
  # B = W = 22
  # C = D = 4
  # D = D = 4
  # E = Q = 16
  # F = X = 23
  # G = X = 23
  # H = H = 8
  # I = I = 9
  # J = C = 3
  # K = I = 9
  # L = X = 23

  Q_real = np.array([7, 22, 4, 4, 16, 23, 23, 8, 9, 3, 9, 23])
  num_runs = 1000
  zero_k = []
  ten_k = []
  twenty_k = []
  thirty_k = []
  hundred_k = []
  five_hundred_k = []
  for i in range(num_runs):
    seed = i * 12345
    zero_k.append(run_simulation(12, 96000000, 0, Q_real, seed))
    ten_k.append(run_simulation(12, 96000000, 10000, Q_real, seed))
    twenty_k.append(run_simulation(12, 96000000, 20000, Q_real, seed))
    thirty_k.append(run_simulation(12, 96000000, 30000, Q_real, seed))
    hundred_k.append(run_simulation(12, 96000000, 100_000, Q_real, seed))
    five_hundred_k.append(run_simulation(12, 96000000, 500_000, Q_real, seed))
    if (i % 100 == 0):
      print(i)



  np.savetxt('zero_k_no_partial.csv', zero_k, fmt='%d', delimiter=', ', header='k = 0', comments='')
  np.savetxt('ten_k_no_partial.csv', ten_k, fmt='%d', delimiter=', ', header='k = 10000', comments='')
  np.savetxt('twenty_k_no_partial.csv', twenty_k, fmt='%d', delimiter=', ', header='k = 20000', comments='')
  np.savetxt('thirty_k_no_partial.csv', thirty_k, fmt='%d', delimiter=', ', header='k = 30000', comments='')
  np.savetxt('hundred_k_no_partial.csv', hundred_k, fmt='%d', delimiter=', ', header='k = 100000', comments='')
  np.savetxt('five_hundred_k_no_partial.csv', five_hundred_k, fmt='%d', delimiter=', ', header='k = 500000', comments='')


  print(np.mean(zero_k))
  print(np.mean(ten_k))
  print(np.mean(twenty_k))
  print(np.mean(thirty_k))
  print(np.mean(hundred_k))
  print(np.mean(five_hundred_k))

  var = np.var(zero_k)
  confidence = 0.95
  n = len(zero_k)
  mean = np.mean(zero_k)
  std_err = stats.sem(zero_k)

  print("mean group size calculated correctly = " + str(np.mean(zero_k)))
  print("group size variance calculated correctly = " + str(np.var(zero_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_zero = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(ten_k)
  confidence = 0.95
  n = len(ten_k)
  mean = np.mean(ten_k)
  std_err = stats.sem(ten_k)

  print("mean group size calculated correctly = " + str(np.mean(ten_k)))
  print("group size variance calculated correctly = " + str(np.var(ten_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_ten = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(twenty_k)
  confidence = 0.95
  n = len(twenty_k)
  mean = np.mean(twenty_k)
  std_err = stats.sem(twenty_k)

  print("mean group size calculated correctly = " + str(np.mean(twenty_k)))
  print("group size variance calculated correctly = " + str(np.var(twenty_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_twenty = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(thirty_k)
  confidence = 0.95
  n = len(thirty_k)
  mean = np.mean(thirty_k)
  std_err = stats.sem(thirty_k)

  print("mean group size calculated correctly = " + str(np.mean(thirty_k)))
  print("group size variance calculated correctly = " + str(np.var(thirty_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_thirty = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(hundred_k)
  confidence = 0.95
  n = len(hundred_k)
  mean = np.mean(hundred_k)
  std_err = stats.sem(hundred_k)

  print("mean group size calculated correctly = " + str(np.mean(hundred_k)))
  print("group size variance calculated correctly = " + str(np.var(hundred_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_hundred = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  var = np.var(five_hundred_k)
  confidence = 0.95
  n = len(five_hundred_k)
  mean = np.mean(five_hundred_k)
  std_err = stats.sem(five_hundred_k)

  print("mean group size calculated correctly = " + str(np.mean(five_hundred_k)))
  print("group size variance calculated correctly = " + str(np.var(five_hundred_k)))

  lower, upper = stats.t.interval(confidence, df=n-1, loc=mean, scale=std_err)

  # print("upper = " + str(upper))
  # print("lower = " + str(lower))

  # print("hmm = " + str(mean - upper))
  # print("hmm = " + str(mean - lower))

  print("Confidence interval = " + str(mean) + " +/- " + str(upper - mean))
  ci_string_size_five_hundred = "Confidence interval = " + str(round(mean, 3)) + " +/- " + str(round(upper - mean, 3))

  print(ci_string_size_zero)
  print(ci_string_size_ten)
  print(ci_string_size_twenty)
  print(ci_string_size_thirty)
  print(ci_string_size_hundred)
  print(ci_string_size_five_hundred)